filter:
    excluded_paths:
        - 'tests/*'

checks:
    php:
        code_rating: true
        duplication: true

build:
    nodes:
        php56:
            environment:
                php: 5.6

            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=clover-file'
                        coverage:
                            file: 'clover-file'
                            format: 'clover'
        php70:
            environment:
                php: 7.0

            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=clover-file'
                        coverage:
                            file: 'clover-file'
                            format: 'clover'
        php71:
            environment:
                php: 7.1

            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=clover-file'
                        coverage:
                            file: 'clover-file'
                            format: 'clover'
